### PR TITLE
pspInstances

### PR DESCRIPTION
**Pull request by ratheilesse**
Randomly generated instances. Some of them were used in the paper "The StockingCost Constraint", CP2014.

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-124
 This will be automatic updated if more commits are added.

**Comment by ChrisJefferson** [comment]
Thanks for your pull request. Could you provide some information on where these instances came from (are they are standard benchmark set, or randomly generated for a paper?).

We should attach some information to what they are.

**Comment by ratheilesse** [comment]
Randomly generated instances. Some of them were used in the paper "The StockingCost Constraint", CP2014.

**Comment by ChrisJefferson** [comment]
Now merged, with a brief metadata added.

**Pull request merged**
