### PR TITLE
replace invalid 6-fractions

### PR DESCRIPTION
**Pull request by arnaud-m**
1/12 + 2/33 + 4/45 + 5/77 + 8/68 + 9/69 = 1/12 + 2/33 + 4/45 + 5/77 + 2/17 + 3/23 = 2958077/5419260 ~= 0.545845
1/12 + 2/33 + 4/45 + 5/78 + 7/69 + 8/69 = 1/12 + 2/33 + 4/45 + 5/78 + 7/69 + 8/69 = 304489/592020 ~= 0.514322
1/12 + 2/33 + 5/49 + 5/79 + 6/78 + 6/84 = 1/12 + 2/33 + 5/49 + 5/79 + 1/13 + 1/14 = 3039823/6642636 ~= 0.457623

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-131
 This will be automatic updated if more commits are added.

**Comment by arnaud-m** [comment]
Are you interested in larger n-fractions ?

**Comment by ChrisJefferson** [comment]
Good catch, not sure how we never checked that. Thank you very much!

**Comment by ChrisJefferson** [comment]
Yes, we would be happy to accept any files giving bigger sets of solutions (probably as a solutions files, you could put one or two more in the problem specification if you like).

**Comment by arnaud-m** [comment]
OK, I will add new solutions soon.

**Pull request merged**
