### PR TITLE
add NuCS

### PR DESCRIPTION
**Pull request by yangeorget**

### CODE REVIEW

**Comment by yangeorget** [comment]
This is a PR for adding NuCS in the languages and NuCS models for some problems.

**Comment by ChrisJefferson** [comment]
Hi, thanks for the contribution!

A couple of comments:

* Firstly, I tried loading a couple of these, and they don't do anything, I assume they still need 'executing' somehow? It might be better to have models that are ready to run (at least with one small example), for people not familiar with your solver. Or could put a comment at the top of the files if I have to do something?
* Just checking, are you fairly sure the interface is fixed? We prefer not to change files on csplib if possible (as people might reference they used a particular model). Just wanted to mention it, in case you were planning any interface changes which might break these files?

**Comment by yangeorget** [comment]
Hello,

Thank you for your comments.
I added a main method to each example and also a comment explaining how to launch the main method.

I don't plan to change the interface which is very stable now.

Best regards,
Yan

**Comment by ChrisJefferson** [comment]
Thanks for the quick answers, I've now merged and updated the website!

**Pull request merged**
