### PR TITLE
Added new Social Golfers model

### PR DESCRIPTION
**Pull request by Druid-of-Luhn**
Added a new model to the Social Golfers problem which has a different constraint from the original one. They both result in the same number of solver nodes, but the new constraint is always faster and also appears clearer.

### CODE REVIEW

**Comment by Druid-of-Luhn** [comment]
On an additional note, @ChrisJefferson mentioned that it is incorrect to use a set of weeks, as it would not allow the case where each golfer plays alone every week. A multiset should be used instead.

Using a multiset of weeks very slightly increases the number of search nodes, but does not change the solve time.

**Comment by ozgurakgun** [comment]
@Druid-of-Luhn thanks for this! I wonder what happens with the different models you get from Conjure, but that is a discussion we can have outside of CSPLib. Feel free to open an issue on the Conjure repo to discuss if you like.

The mset --> set thing is indeed implied, but having a set helps a lot, so we do that.

**Comment by ozgurakgun** [comment]
I am wondering if we should just keep a single Essence file instead of this though. The decision variable doesn't change, it's only the constraint that does. We could keep the old one in a comment. We could even have both of the constraints...

**Comment by ChrisJefferson** [comment]
It's not implied, if we have 12 golfers in 12 groups (for example) then different weeks can be identical.

**Comment by Druid-of-Luhn** [comment]
I think it would be better to have only one model in this case. If there is a format you prefer for keeping both constraints in one model, I can update it.

**Comment by ozgurakgun** [comment]
I think we should just keep your model @Druid-of-Luhn -- it looks nicer.

We should also update the spec to exclude solutions without any socialisation. Golfers shall socialise!

**Comment by ozgurakgun** [comment]
I created #169 to track the edge case. Merging this. Thanks @Druid-of-Luhn!

**Pull request merged**
