### PR TITLE
Wordpress

### PR DESCRIPTION
**Pull request by BogdanD02**
Hello,
I would like to add the Wordpress Problem as problem nr. 90. The problem looks into Cloud Deployment of component-based applications (e.g. Wordpress). I think you too will find it interesting, as not only it scales with the number of Virtual Machine offers at our disposal, but also with the number of components. Please do let me know what changes are necessary.

All the best,
Bogdan David

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Hi, sorry for slow reply to this post.

In principle this problem looks good. It looks like you haven't quite finished the description? (There are some ??? and comments at the end?)

**Comment by BogdanD02** [comment]
Hello,
I updated the files to their latest version. The moment I made the request, I must've uploaded a draft to Github without noticing. Thanks a lot for pointing that out to me. 

If anything else must be modified please let me know.
Best regards,
Bogdan David

**Comment by BogdanD02** [comment]
Hi,

Did you manage to have a look over our pull request ? I would really like to get some feedback so I can make any additional changes required and merge the PR.

Thanks,
Bogdan David

**Comment by ChrisJefferson** [comment]
Hi, thanks!

I had to do a "git rebase" (and merge some of your commits), and make one change (unfortunately csplib's website generator doesn't support directories in the Models directory, so I had to 'zip' up your models.

I've made a new PR for this, which I'll merge and upload to the website -- please have a look and let me know if you see any issues!

**Comment by ChrisJefferson** [comment]
This is (and has been for a while) live on the website, let me know if you see any issues

**Comment by ChrisJefferson** [comment]
I'm going to close this PR as I believe this is all merged, but let me know if there are any issues.

**Pull request closed without merging**
