### PR TITLE
Stochastic

### PR DESCRIPTION
**Pull request by hemmidavid**
I would like to add a problem that I have used for a CPAIOR 2017 paper. I have created a new category called "Stochastic Constraint Programming" as I expect to upload further problems in this category. 

Thanks

### CODE REVIEW

**Comment by hemmidavid** [comment]
initial pull request

**Comment by ozgurakgun** [comment]
Thanks for this @hemmidavid.

May I suggest including the Python scripts as they are instead of using a zip file? They could still be grouped under a directory if you like.

**Comment by hemmidavid** [comment]
@ozgurakgun I can no longer build the csplib if I unzip the python instances, how do I resolve that?

**Comment by ozgurakgun** [comment]
Oh, what kind of an error do you get?

**Comment by hemmidavid** [comment]
I have fixed the problem that caused a building error (I had subdirectories in the data folder). Do you want me to make any further changes?

Thanks,

**Comment by ozgurakgun** [comment]
That all looks good, thanks. The preview build didn't work (our fault, not yours). If you don't mind I'll look into fixing that before merging this. It shouldn't take too long.

**Comment by hemmidavid** [comment]
That works for me, thanks!

**Comment by ozgurakgun** [comment]
@hemmidavid, we solved the problem on our side and merged this PR. Thanks for the contribution!

**Pull request merged**
