### PR TITLE
"how to"s

### PR DESCRIPTION
**Pull request by ozgurakgun**
In the CSPLib sprint event people requested documentation for some sample workflows.

I have started writing something between a "frequently asked questions" and a "how to do X guide" thingy.

Clearly we cannot write and maintain a Git/GitHub tutorial, but having some specific cases written down won't hurt.

This is work-in-progress, so please do not merge yet. I intend to deal with the TODO notes I left in there soon and then merge it. After that we can update it as the need arises/we think of new subjects to document. It should probably be linked to from the README too.

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-151/
 This will be automatically updated if more commits are added. If travis-ci is busy it may take ~10 minutes for the build to appear

**Comment by Bilalh** [comment]
For 'simple' edits e.g. I just want to add a bibtex reference,  or  improve the description, this can be done completely though the github interface.  e.g.  say the user is at http://csplib.org/Problems/prob002/ they click the edit button which takes them to the github page, they then click the edit button  to edit it in their browser and github makes the pull request for them.

There also wiki of questionable use, that IanG created https://github.com/csplib/csplib/wiki and never finished.

**Comment by ozgurakgun** [comment]
Good point @Bilalh, the simple edits thing is something I wanted to include. 

I am not sure about the wiki, but including a how-to-guide in the repository won't hurt in any case.
A wiki is better if people create content, but let's be honest we will have to write most of this ourselves. :)

**Comment by Bilalh** [comment]
I think wiki is pointless and should be removed. Having your help text in the repo and linked from csplib is a much better idea.   Oddly enough the wiki was your idea.

**Comment by Bilalh** [comment]
Also   [prob006]   links to a problem,  using the prob006 as the text.

**Comment by ozgurakgun** [comment]
I mean a wiki could have worked as well. But anyway. As long as it gets done in some way I am happy.

**Comment by Bilalh** [comment]
It could have but based of the fact that it was never edited after IanG created it, I think that idea failed.

**Comment by Bilalh** [comment]
Might want to mention you need Python 3.3+ (Python 3.4+ on windows).  Also would it make sense to put the simpler edits section first to attract the people, that think it too much effort to contribute?

**Comment by ozgurakgun** [comment]
@ChrisJefferson I had started writing this just after CP2016. I had some TODO notes left in it, which I now took care of. Should we link to it from somewhere in the main website?

Currently it is just a single markdown file in the repository.

**Pull request merged**
