### PR TITLE
Bibtex reformatted

### PR DESCRIPTION
**Pull request by Bilalh**
PR to test travis script

### CODE REVIEW

**Comment by ozgurakgun** [comment]
What did you use for the bibtex formatting?

**Comment by Bilalh** [comment]
I used my program  https://github.com/Bilalh/bibtex-format that I have used for years.   It written in haskell for some reason so you  might be interested in it.   Binaries for OS X  can be found at https://github.com/Bilalh/bibtex-format/releases .

**Comment by ozgurakgun** [comment]
Heh! I had written something similar a while back too: https://github.com/ozgurakgun/bibtex-clean

Yours look more complicated though, there are even binary releases!

Anyway, we both seem to like wasting our time on similar things. :)

**Comment by Bilalh** [comment]
Oddly enough they very similar we even have define same op for flip.  I actually made the binary release 30 minutes ago (after spending a while getting travis to build haskell correctly,  It  can now built it <5 min!), since some else might want to use it.    

```
(|>) :: a -> (a -> b) -> b
(|>) = flip ($)
```

**Pull request merged**
