### PR TITLE
add Rotating Nurse Rostering problem

### PR DESCRIPTION
**Pull request by chillja**
Hello everyone,
we'd like to add the Rotating Rostering Problem as problem nr 087. The problem was crafted from real world requirements and has been utilised in a number of published articles. We hope the problem is considered valuable and the description and models are up to standard.

All the best, on behalf of our group
Ilja Becker

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
Dear Ilja, thanks for your submission!

This is mostly perfect, the only issue I have is the "Formalised CSP", as we have some users who are blind, so wouldn't be able to read the equations in your png.

However, you should be able to just put latex inline, and I imagine this png was generated from some latex? If you have the latex, I'm happy to try putting it in, and see if it works smoothly.

**Comment by chillja** [comment]
Dear Chris,
that makes sense, thanks. I didn't know the website could handle inline Latex, which is why we went with the png. If you could give me a hint how I'd need to escape that I'll put it right in myself. Alternatively I've put the tex-code [here](https://gist.github.com/chillja/27546e44457f5ab13a9509969cccbd44.js").

Thankes for the help.

**Comment by ChrisJefferson** [comment]
Hi,

I have (I hope) transfered the picture into markdown tex -- it's in the "new tex" branch, feel free to take a look! If you like, I can just merge it in, and you can check it out live.

**Comment by chillja** [comment]
Hi Chris,
thank you very much for the effort. I took the liberty and cherry picked your commit and added some further changes. I reverted the variables in X back to lowercase to better distinguish them against the set and the matrix. Further I used the inline latex in the rest of the specification and the data text, looks much better now - thanks again. I think it should be ready now.

**Comment by chillja** [comment]
Is there any open issues I would need to address for this PR?

**Comment by ChrisJefferson** [comment]
No, sorry, I just didn't merge it!

**Pull request merged**
