### PR TITLE
Essence changes

### PR DESCRIPTION
**Pull request by ozgurakgun**
This pull request contains quite a few commits, but hopefully nothing should be controversial (or conflicting with others).

I added Essence files to quite a few existing problems. Moreover I created some new problems from the Essence Catalog.

I will try to add some more Essence models later and also go through the old ones to look out for bit-rot.

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-117
 This will be automatic updated if more commits are added.

**Comment by ozgurakgun** [comment]
@Bilalh and/or @ChrisJefferson can you give me a "code review" for this one please? I don't want to merge all this without someone else taking a look.

**Comment by Bilalh** [comment]
Looks good, some minor points 

There some BiBTeX in Problems/prob045/models/CoveringArray.essence that not in the reference section,  which should probably be move/copied.

prob115 & prob131 are hard to read, add some line breaks?

Some of the urls point to the old urls e.g (http://www.csplib.org/prob/prob002/)  from  Problems/prob002/models/TemplateDesign.essence. While I put redirects in so that it will resolve every  url I found in publication correctly (http://www.csplib.org/Problems/prob002/ in this case) should we be publicising these old url?

**Comment by ozgurakgun** [comment]
Thanks @Bilalh. I did a search-and-replace to update all csplib.org/prob/X style links. This means the pull request touches files other than only the .essence models.

**Comment by ChrisJefferson** [comment]
Looks good to me!

**Pull request merged**
