### PR TITLE
Create prob009.java

### PR DESCRIPTION
**Pull request by thmour**
Problem 009 solved in java using JaCoP for a university project

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-135
 This will be automatic updated if more commits are added.

**Comment by ChrisJefferson** [comment]
This looks good. One small request, could you attach a license to the file ( https://creativecommons.org/licenses/by/4.0/ is the one we use for the rest of csplib, but you can use another license if you like, like the GPL and BSD license ).

This is just a technical issue with source code.

**Comment by thmour** [comment]
added the MIT one

**Comment by ChrisJefferson** [comment]
Thanks, merged. Will appear on the website within a couple of days.

**Pull request merged**
