### PR TITLE
added pmtsp

### PR DESCRIPTION
**Pull request by svancauw**
Add PMTSP + instances

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-160/
 This will be automatically updated if more commits are added. If travis-ci is busy it may take ~10 minutes for the build to appear

**Comment by ozgurakgun** [comment]
@Bilalh any idea why the preview build is missing?

**Comment by Bilalh** [comment]
@ozgurakgun  I looking into it at the moment.

**Comment by ozgurakgun** [comment]
Thanks for looking into it @Bilalh!

**Pull request merged**
