### PR TITLE
create prob063 on winner determination

### PR DESCRIPTION
**Pull request by pprosser**

### CODE REVIEW

**Comment by csplib-robot-pr** [comment]
Build preview located at http://csplib.github.io/csplib-PR-builds/PR-137
 This will be automatic updated if more commits are added.

**Comment by ozgurakgun** [comment]
@Bilalh any idea why this build preview gives a 404? The files for PR-137 seem to be there in the PR-builds repository.

**Comment by Bilalh** [comment]
@ozgurakgun  it works for me. e.g. http://csplib.github.io/csplib-PR-builds/PR-137/Problems/prob063/  Works on my phone.  Try again? It may have taken a few minutes for GitHub pages to update it caches.

**Comment by ozgurakgun** [comment]
The index page still doesn't seem to work:  http://csplib.github.io/csplib-PR-builds/PR-137

**Comment by Bilalh** [comment]
You are missing a slash it should be http://csplib.github.io/csplib-PR-builds/PR-137/

**Comment by ozgurakgun** [comment]
Hah! The link generated by the build bot missed the slash too. We should fix that!

Maybe we can also change the word "automatic" to "automatically" in its message when doing so. Can you have a look at that Bilal?

**Comment by Bilalh** [comment]
Ok

**Comment by Bilalh** [comment]
PR-137 is the oddity since   http://csplib.github.io/csplib-PR-builds/PR-136 works. I still change it to make it more robust.

**Comment by ozgurakgun** [comment]
Thanks a lot Bilal!

**Pull request merged**
